### ISSUE TITLE
Mobile Web Integration shows Undefined Ad

### ISSUE THREAD

**Issue by ifabijanovic** [mopub/mopub-client#121]
Hello!
The MoPub Mobile Web Integration recently started showing empty Ad banners containing just the text "Undefined". The issue seems to occur only when Ad is not retrieved from the server.

When request to ads.mopub.com/m/ad?id=... returns a response with "is_filled": true and "ad" set to some HTML, banner is rendered correctly. When the same request returns a response with "is_filled": false the above issue occurs.

**Comment by blogvinskiy** [comment]
@vvlahek Sorry for the delay on this. We're looking into the issue and should have it resolved shortly. Will let you know once we have a fix out.

**Comment by blogvinskiy** [comment]
@vvlahek Apologies for the delay. This has now been fixed, so you shouldn't see this issue anymore.

**Comment by blogvinskiy** [comment]
@vvlahek Apologies for the delay. This has now been fixed, so you shouldn't see this issue anymore.

**Comment by blogvinskiy** [comment]
@vvlahek Apologies for the delay. This has now been fixed, so you shouldn't see this issue anymore.
